### ISSUE TITLE
Use environmental variables for config options

### ISSUE THREAD

**Issue by john-lowry** [imperva/incapsula-cli#1]
In order to not store credentials in plaintext on disk so accidentally getting them stored on .bash_history, can we get the option to pull api_key, api_id, account, baseUrl, and repo from environmental variables. Also aligns well with a lot CI/CD pipelines.

I propose the following environmental variables:

INCAP_KEY
INCAP_ID
INCAP_ACCOUNT
INCAP_URL
INCAP_REPO

**Comment by joeymoore** [comment]
John, sorry for the long time between updates. I have been making several changes and just found out that I don't have access to the repo anymore. I will be that resolved and add the request to the backlog.

**Comment by joeymoore** [comment]
This functionality has been added in the latest v2 branch.

**Comment by joeymoore** [comment]
@john-lowry did you get a chance to apply this yet?
