### ISSUE TITLE
incap site list_incaprule not showing redirect rules

### ISSUE THREAD

**Issue by AJGilDiaz** [imperva/incapsula-cli#12]
Hi, 

I have configured some redirect rules but those are not showing up in "incap site list" 

INFO - You have no Redirect Rules!!! <----- but isn't true I have some configured
INFO - You have no Forward Rules!!!
INFO - You have no Rewrite Rules!!!

However I can see them on the backup file under policy rules.

**Comment by joeymoore** [comment]
Yes sir, this was added to the API and platform after I finished this CLI version, I hope to release a newer version that includes this soon.

**Comment by AJGilDiaz** [comment]
Hi Joe, 

Thank you for the update, I'll close this then.

Regards,
