### ISSUE TITLE
Site List Results Incomplete

### ISSUE THREAD

**Issue by joserh-git** [imperva/incapsula-cli#15]
Hello, 

We are seeing inconsistent behavior when running the command to list sites. We had one end user successfully run the command "incap site list" and it displayed all 100 websites. Another user ran the command and it only displayed 47 of the sites (see attached sanitized image). 

It almost appears as if the command gets timed out and therefore pulls incomplete information. Here is the affected users info:

User1:
Python 3.10.5
pip 22.1.2

User2:
Python 3.6.8
pip 9.0.3

User1 appears to not be affected by incomplete info but User2 seems to be affected by incomplete script output. Please let me know if you need additional information. 

<img width="430" alt="Incap CLI Incomplete List Sanitized" src="https://user-images.githubusercontent.com/70404051/184935208-ccc9e283-b83b-4b64-83ff-6a8bd22dd581.png">

**Comment by joeymoore** [comment]
Fixed with github.com/imperva/incapsula-cli/pull/24
