### ISSUE TITLE
site status [siteid] fails

### ISSUE THREAD

**Issue by tristandostaler** [imperva/incapsula-cli#2]
When we don't have countries but rather a list of continents setup in the blacklisted contries field, when we run site status [siteid], it fails because:
in incapsula-cli\root\src\Sites\site.py line 142:
print('The following countries are blacklisted: %s' % ', '.join(aclRules['geo']['countries']))

aclRules contains the following:
geo, exceptions, id, name

And then aclRules['geo']:
continents

So the correct line in my context would be:
print('The following countries are blacklisted: %s' % ', '.join(aclRules['geo']['continents']))
though that wouldn't work if there are contries.

I want to propose this:
elif aclRules['id'] == 'api.acl.blacklisted_countries':
                    if "countries" in aclRules['geo']:
                        print('The following countries are blacklisted: %s' % ', '.join(aclRules['geo']['countries']))
                    if "continents" in aclRules['geo']:
                        print('The following continents are blacklisted: %s' % ', '.join(aclRules['geo']['continents']))

**Comment by joeymoore** [comment]
Hi, sorry for the long time between updates. I have been making several changes and just found out that I don't have access to the repo anymore. I will be that resolved and add the request to the backlog.

**Comment by tristandostaler** [comment]
Ok thanks!

**Comment by joeymoore** [comment]
Resolved with your logic
