### ISSUE TITLE
Description of "site list " is incorrect and refers to a delete

### ISSUE THREAD

**Issue by xlash** [imperva/incapsula-cli#4]
$ python.exe src/incap.py site -h
usage: incap site <command> [options]

positional arguments:
  {add,restore,delete,status,upcert,delcert,list,configure,security,acl,add_incaprule,edit_incaprule,del_incaprule,list_incaprule,whitelist,cache-mode,cache-rule,advanced-cache}
    add                 Add a new site to an account. If the site already
                        exists, its status is returned.
    restore             Use this operation to bulk add sites.
    delete              Use this operation to delete a site.
    status              Use this operation to get the status of a site.
    upcert              Use this operation to upload custom certificate for
                        your site. The following SSL certificate file formats
                        are supported: PFX, PEM, CER.
    delcert             Use this operation to upload custom certificate for
                        your site. The following SSL certificate file formats
                        are supported: PFX, PEM, CER.
    list                **Use this operation to delete a site.**

**Comment by joeymoore** [comment]
Thank you for bringing this to my attention.
