### ISSUE TITLE
getting started with development env

### ISSUE THREAD

**Issue by mihaiturcu** [imperva/incapsula-cli#7]
Hello,

Trying to figure out how to work on contributing to this project.
Traceback (most recent call last):
  File "/Users/something/incapsula-cli/cwafcli/__main__.py", line 2, in <module>
    from .Utils import clidriver
ImportError: attempted relative import with no known parent package

Seems like all packages are prefixed with a . whereas the actual subfolders where the python files live do not have that. 
Additionally from what I've revied in the gitignore file, you're using VSCode for development and excluding a "build" folder.
How to you get to build these *.pyc files or to the result that pip3 brings you when installing.

**Comment by joeymoore** [comment]
Hello @mihaiturcu and sorry for the slow response, please let me know if you still need assistance with this.
I use PyCharm for an IDE.
